Email service
Best-offer-finder/backend pull request #19
Opened 2024-06-07 08:40 UTC by MaciejSieradz

2024-06-07 21:16 UTC, Vertonowsky commented on src/main/java/com/example/backend/email/EmailService.java
> +    public void sendEmail(String to, String subject, String body) {
Gdzie wywołanie tej funkcji? Email sam się nie wyśle

2024-06-07 21:16 UTC, Vertonowsky commented on src/main/java/com/example/backend/email/EmailService.java
> +        message.setText(body);
zróbmy body jako szablon html

2024-06-07 21:16 UTC, Vertonowsky commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/best?useUnicode=yes&characterEncoding=UTF-8
?

2024-06-07 21:16 UTC, Vertonowsky commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-id=16076245667-2h3dja4a1kn834c4ong5q2m1s6chmdjh
? Raz zostawiamy puste, a raz leakujemy?

2024-06-07 21:30 UTC, MaciejSieradz commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/best?useUnicode=yes&characterEncoding=UTF-8
Zapomniałem usunąć jak propertiesy były dodawane dla wiktora

2024-06-07 21:30 UTC, MaciejSieradz commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-id=16076245667-2h3dja4a1kn834c4ong5q2m1s6chmdjh
jak wyżej

2024-06-07 21:30 UTC, MaciejSieradz commented on src/main/java/com/example/backend/email/EmailService.java
> +    public void sendEmail(String to, String subject, String body) {
Dorób sobie tam gdzie chcesz

2024-06-08 08:42 UTC, Vertonowsky commented on src/main/java/com/example/backend/email/EmailService.java
> +    public void sendEmail(String to, String subject, String body) {
Zrób tak jak w zadaniu - "Wysyłka maila w momencie znalezienia nowych produktów".

Uwzględnij w tytule maila nazwę schematu i ilość znalezionych aut.

2024-06-08 08:43 UTC, Vertonowsky requested changes

2024-06-08 08:43 UTC, Vertonowsky commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/best?useUnicode=yes&characterEncoding=UTF-8
cofnijmy z PR

2024-06-08 08:43 UTC, Vertonowsky commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-id=16076245667-2h3dja4a1kn834c4ong5q2m1s6chmdjh
cofnijmy z PR

2024-06-10 17:16 UTC, Vertonowsky approved these changes

2024-06-11 08:28 UTC, kestivvi approved these changes

2024-06-11 08:31 UTC, merged